function fj = fj(z)
q1 = z(1);
q2 = z(2);
q3 = z(3);
q4 = z(4);
q5 = z(5);
u1 = z(6);
u2 = z(7);
u3 = z(8);
u4 = z(9);
u5 = z(10);

%FJ
%    FJ = FJ(Q2,Q4,U1,U2,U3,U4,U5)

%    This function was generated by the Symbolic Math Toolbox version 5.9.
%    14-Oct-2015 12:19:41

fj = [u1.*(-1.0e-4);q2.*(-3.6363e2)-u2.*1.0e-4;u3.*(-1.0e-4);q4.*-3.0e2-u4.*1.0e-4;u5.*(-1.0e-4)];
